if has("gui")
    if has("gui_macvim")
        set fuoptions=maxhorz,maxvert
        " Command-T
        " macmenu &File.New\ Tab key=<D-T>
        " map <D-t> :CommandT<CR>
    endif
    set visualbell
endif
